# **NumPy**

This notebook introduces the basic usages of NumPy library, such as NumPy array, array arithematics, and array broadcasting etc

\

Instruction: type your code when you see 'Type your code here' in comments

 # **Array Creation/Manipulation**



Declare an Array using **np.array()**

Reshape an Array using **reshape()** or **ravel()**


In [82]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])  #create a 4x3 array
print("ndarray x:\n", x)
print("Shape of x:", x.shape)
print("\n")



ndarray x:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of x: (4, 3)




## Example: Reshape the array x into a column vector

In [83]:
x = np.arange(1,13)
y1 = x.reshape(-1,1) 
print("After reshape:\n", y1)
print("Shape of y1:", y1.shape)
print("\n")


After reshape:
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Shape of y1: (12, 1)




## Exercise 1: Reshape the array x into a 3x4 array

In [84]:
x = np.arange(1,13)
y2 = x.reshape(3,4)
print("After reshape:\n", y2)
print("Shape of y2:", y2.shape)
print("\n")



After reshape:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of y2: (3, 4)




##Exercise 2: Reshape the array x into a 2x2x3 array

In [85]:
x = np.arange(1,13)
y3 = x.reshape(2,2,3)
print("After reshape:\n", y3)
print("Shape of y3:", y3.shape)
print("\n")



After reshape:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of y3: (2, 2, 3)




##Exercise 3: Flatten the array y3

In [86]:
z = y3.reshape(1,-1)
print("After flatten:\n", z)
print("Shape of z:", z.shape)
print("\n")

After flatten:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
Shape of z: (1, 12)




#**Array Arithmetic**


**If the two arrays have same shape, elementwise operation can be performed.**

##Exercise 4: Same shape arrays arithmetic

Create an Array_b using np.arange() which has a same shape as the Array_a.

In [87]:

Array_a = np.array([[6,20,3,14],[2,10,5,10]])
Array_b = np.arange(1,9).reshape(2,4)    
print(np.shape(Array_b))               #type your code here


(2, 4)


Add array a with array b, and print out the result array.

In [88]:
result = Array_a + Array_b                          #type your code here
print("Array_a + Array_b = \n", result)     

Array_a + Array_b = 
 [[ 7 22  6 18]
 [ 7 16 12 18]]


Subtract Array_b from Array_a ( i.e. Array_a - Array_b ), and print out the result array.

In [89]:
#type your code here
result0 = Array_a - Array_b
print("Array_a - Array_b = \n", result0) 

Array_a - Array_b = 
 [[ 5 18  0 10]
 [-3  4 -2  2]]


Multipy Array_a by Array_b, and print out the result array.

In [90]:
#Type your code here
result1 = Array_a * Array_b
print("Array_a * Array_b = \n", result1) 


Array_a * Array_b = 
 [[ 6 40  9 56]
 [10 60 35 80]]


Compare Array_a with Array_b (Using == to check the equality), and print out the result array.

In [91]:
#Type your code here
print(Array_a == Array_b)


[[False False  True False]
 [False False False False]]


Compare Array_a with Array_b (using < / > / <= / >= to check the inequlity), and print out the result array.

In [92]:
#type your code here
print(Array_a > Array_b)
print(Array_a < Array_b)
print(Array_a >= Array_b)
print(Array_a <= Array_b)



[[ True  True False  True]
 [False  True False  True]]
[[False False False False]
 [ True False  True False]]
[[ True  True  True  True]
 [False  True False  True]]
[[False False  True False]
 [ True False  True False]]


#**Array Broadcasting**


**If the arrays have different shapes, the operations can be broadcasted.** 

**The smaller array will be broadcasted across the larger array**

In [93]:
Array_x = 2                     #a is a scalar
Array_y = np.array([2,3,4,5])   #b is a 1x4 array

##Exercise 5: Scalar Arithmetic

Similar to what you did for same shape arrays, try to perform the arithmetic opertaions to different shape arrays ( Array_x and Array_y ), and observe the result.

Addition:

In [94]:
#type your code here 
print(Array_x + Array_y)


[4 5 6 7]


Subtraction:

In [95]:
#type your code here 
print(Array_x - Array_y)


[ 0 -1 -2 -3]


Multiplication:

In [96]:
#type your code here 
print(Array_x * Array_y)


[ 4  6  8 10]


Division:

In [97]:
#type your code here 
print(Array_x / Array_y)

[1.         0.66666667 0.5        0.4       ]


Equality comparision:

In [98]:
#type your code here 
print(Array_x == Array_y)


[ True False False False]


Inequality comparision:

In [99]:
#type your code here 
print(Array_x > Array_y)
print(Array_x < Array_y)
print(Array_x >= Array_y)
print(Array_x <= Array_y)


[False False False False]
[False  True  True  True]
[ True False False False]
[ True  True  True  True]


## Example: Multipy a 2x3 Array with 1x3 Array

In [100]:
Array_a = np.arange(1,7).reshape(2,3)  # 2x3 array
print("Array_a:\n", Array_a)
print("Shape of Array_a:", Array_a.shape)
print("\n")

Array_b = np.array([0,2,1]) #row vector
print("Array_b:\n", Array_b)
print("Shape of Array_b:", Array_b.shape)
print("\n")

print("Result of Array_a * Array_b :\n", Array_a * Array_b)#b will be treated as 
                                            #[[0,2,1]
                                            #[0,2,1]]
print("Shape of Array_a * Array_b :\n", (Array_a * Array_b).shape)

Array_a:
 [[1 2 3]
 [4 5 6]]
Shape of Array_a: (2, 3)


Array_b:
 [0 2 1]
Shape of Array_b: (3,)


Result of Array_a * Array_b :
 [[ 0  4  3]
 [ 0 10  6]]
Shape of Array_a * Array_b :
 (2, 3)


## Exercise 6: Multipy a 2x3 Array with 2x1 Array

Multipy Array_a by column vector, and print out the result array.

In [101]:
Array_a = np.arange(1,7).reshape(2,3)  # 2x3 array
#You need to transform Array_a into:
#[[0, 0, 0]
#[8, 10, 12]]
#by multiplying Array_a with Array_c

Array_c = np.array([[0],
           [2]]) #Type your code here
     #Array_c should be column vector
print("Result of Array_a*Array_c:\n", Array_a*Array_c)
print("Shape of Array_a * Array_c :\n", (Array_a * Array_c).shape)

Result of Array_a*Array_c:
 [[ 0  0  0]
 [ 8 10 12]]
Shape of Array_a * Array_c :
 (2, 3)


# **Common Mathematical/Statistical Functions**

##Example:

In [102]:
a = np.arange(1,13).reshape(4,3)  #4x3 array
print("nparray a:\n", a)
print('Shape of a:', a.shape, '\n')

#mean
print("mean:\n", np.mean(a))

#max
print("max value:\n", np.max(a))

#sum
print("sum:\n", np.sum(a))

#standard deviation
print("standard deviation:\n", np.std(a))

#variance
print("variance:\n", np.var(a))
print("\n")

nparray a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of a: (4, 3) 

mean:
 6.5
max value:
 12
sum:
 78
standard deviation:
 3.452052529534663
variance:
 11.916666666666666




In [103]:
a = np.arange(1,13).reshape(4,3)  #4x3 array
print("nparray a:\n", a)
print('Shape of a:', a.shape)

#mean
print("mean:\n", np.mean(a, axis=0))

#max
print("max value:\n", np.max(a, axis=0))

#sum
print("sum:\n", np.sum(a, axis=0))

#standard deviation
print("standard deviation:\n", np.std(a, axis=0))

#variance
print("variance:\n", np.var(a, axis=0))
print("\n")

nparray a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of a: (4, 3)
mean:
 [5.5 6.5 7.5]
max value:
 [10 11 12]
sum:
 [22 26 30]
standard deviation:
 [3.35410197 3.35410197 3.35410197]
variance:
 [11.25 11.25 11.25]




In [104]:
a = np.arange(1,13).reshape(4,3)  #4x3 array
print("nparray a:\n", a)
print('Shape of a:', a.shape)

#mean
print("mean:\n", np.mean(a, axis=1))

#max
print("max value:\n", np.max(a, axis=1))

#sum
print("sum:\n", np.sum(a, axis=1))

#standard deviation
print("standard deviation:\n", np.std(a, axis=1))

#variance
print("variance:\n", np.var(a, axis=1))
print("\n")

nparray a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of a: (4, 3)
mean:
 [ 2.  5.  8. 11.]
max value:
 [ 3  6  9 12]
sum:
 [ 6 15 24 33]
standard deviation:
 [0.81649658 0.81649658 0.81649658 0.81649658]
variance:
 [0.66666667 0.66666667 0.66666667 0.66666667]




##Exercise 7: Calculate sum of series

In [105]:
#Calculate 2+4+6+8+....+100

a = np.arange(1,101,2 )#Type your code to create numpy array using np.arange
result = a.sum() #Type your code to calculate the sum of the numpy array
print("2+4+6+8+....+100 = ", result) #The result should be 2550

2+4+6+8+....+100 =  2500


# **Note about NumPy array**

Changing an element of b_list won't affect the elements of a_list

In [106]:
a_list = [0,1,2,3,4,5]
print(a_list)

b_list = a_list[1:4]      
print(b_list)

[0, 1, 2, 3, 4, 5]
[1, 2, 3]


In [107]:
b_list[0] = 1000  #Change the first element in the b_list to 1000

In [108]:
print(a_list)
print(b_list)

[0, 1, 2, 3, 4, 5]
[1000, 2, 3]


But changing an element of b_array will also change the corresponding element of a_array

In [109]:
#@title
a_array = np.array([0,1,2,3,4,5])
print(a_array)
b_array = a_array[1:4]
print(b_array)



[0 1 2 3 4 5]
[1 2 3]


In [110]:
b_array [0] = 1000   #Change the first element in the b_array to 1000

In [111]:
print(a_array)
print(b_array)

[   0 1000    2    3    4    5]
[1000    2    3]


You need to create a new instant of an array when creating b_array if you don't want to alter a_array when altering b_array

In [112]:
#@title
a_array = np.array([0,1,2,3,4,5])
print(a_array)
b_array  = a_array[1:4].copy() # or b_array  = np.array(a_array [1:4])

print(b_array)



[0 1 2 3 4 5]
[1 2 3]


In [113]:
b_array [0] = 1000

In [114]:
#@title
print(a_array)
print(b_array)

[0 1 2 3 4 5]
[1000    2    3]
